### ISSUE TITLE
Migrate production pricenodes to v0.7.0

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq-pricenode-deprecated#4]
Per #2 and #3, the new home of `bisq-pricenode` source code is here in the bisq-network/pricenode repository.

@bisq-network/pricenode-operators, this issue is about migrating your production pricenodes from 0.6.4 to 0.7.0.

The code has not changed significantly in this move, but the way the pricenode is started up has changed. You can see complete instructions in the README of this repository.

To be conservative, we should probably do this migration one node at a time, while watching the logs pretty closely on each to ensure nothing goes wrong.

I suggest we do it in the following order:

 - [x] @ManfredKarrer migrates the first of his nodes, and watches in closely
 - [x] @ManfredKarrer migrates his other two nodes
 - [x] @mrosseel migrates his node
 - [x] @Emzy migrates his node

Sound good to everyone? Please let me know what questions you have, and let's coordinate in the Slack `#pricenode` channel as necessary. Thanks!

**Comment by cbeams** [comment]
Note that I have not actually tagged `v0.7.0` yet. I'd like to have @ManfredKarrer work from master to try this out, and if everything looks good, then we can tag the release.

Note that I am not building this as an executable jar at the moment, but we can do that if it's important. As per the README, it's essentially designed to be built and run from source right now.

**Comment by ManfredKarrer** [comment]
I run the new version now.

**Comment by cbeams** [comment]
> I run the new version now.

Great. It's been three days now, and it sounds like there haven't been any issues.

@mrosseel and @Emzy, could you update now as well?

**Comment by mrosseel** [comment]
Upgrading now, had to adapt my Dockerfile to use gradle. Still using the old loop scripts waiting for resolution of #6 
Will PR the docker setup to the pricenode repo soon.

**Comment by mrosseel** [comment]
There was already a PR, #1 , please review

**Comment by ManfredKarrer** [comment]
I have not seen any issues with the change. I think it is safe of @mrosseel  and @Emzy move over to the new model as well.

**Comment by Emzy** [comment]
My node running vesion 0.7.0. now.

**Comment by cbeams** [comment]
Closing as complete, thanks all!

I’ll follow up soon in a separate issue / conversation about upgrade procedures going forward.
